version: '3'
services:
  financepostgres:
    image: postgres:latest
    container_name: finance_backend
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_DB=finance_web
      - POSTGRES_USER=finance_web
      - POSTGRES_PASSWORD=ditiseensecuurwachtwoordvoormij
    # volumes: 
    #   - postgres:/var/lib/postgresds